# Generated by Django 4.2.3 on 2023-07-14 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselrecomment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_jar_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
