# Generated by Django 4.2.3 on 2023-07-14 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_counselrecomment_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarpost',
            name='like_users',
            field=models.ManyToManyField(default=0, related_name='like_jar_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counselrecomment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_recomment_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
