# Generated by Django 4.2.3 on 2023-07-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_jarpost_like_users_alter_counselrecomment_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('comment_like', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_jar_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jar_comment', to='post.jarpost')),
            ],
        ),
        migrations.AddField(
            model_name='counselcomment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_counsel_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JarRecomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomment', models.TextField()),
                ('recomment_like', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jar_recomment', to='post.jarcomment')),
                ('like_users', models.ManyToManyField(related_name='like_jar_recomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
