# Generated by Django 4.2.3 on 2023-07-14 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_alter_counselpost_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselpost',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_counselposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
