# Generated by Django 4.2.3 on 2023-07-14 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_alter_counselpost_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselcomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_counsel_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counselrecomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_recomment_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jarcomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_jar_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jarpost',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_jar_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jarrecomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_jar_recomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
